export interface ILang {
    INPUT_SEARCHTEXT: string,
    INFOTEXT: string,
    NOTHING_FOUND: string,
    NIGHT: string,
    MORNING: string,
    NOON: string,
    EVENING: string,
    WEATHER_FOR: string,
    AT: string,
    TO: string,
    PRESSURE: string,
    CLOUDS_TTP: string,
    WIND_TTP: string,
    FEELS_LIKE_TTP: string,
    RAIN_TTP: string,
    HUMIDITY_TTP: string,
    ERROR: string,
}