export const WEATHER_DATA_LOADING:string  = "CURRENT_WEATHER_DATA_LOADING";
export const WEATHER_DATA_LOADED:string   = "CURRENT_WEATHER_DATA_LOADED";
export const LOADING_ERROR:string         = "LOADING_ERROR";